"""dexcription added to product and removed from permission

Revision ID: 0811bd7174d1
Revises: f221f5c12461
Create Date: 2023-07-02 18:46:56.954418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0811bd7174d1'
down_revision = 'f221f5c12461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
