"""bug1

Revision ID: 1fcffea0c4a0
Revises: ba8f6f7a775d
Create Date: 2023-06-21 12:13:09.109505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fcffea0c4a0'
down_revision = 'ba8f6f7a775d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=mysql.SMALLINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=mysql.SMALLINT(),
               nullable=False)

    # ### end Alembic commands ###
