"""name instead of path in product-image

Revision ID: 3af8b575089f
Revises: 0811bd7174d1
Create Date: 2023-07-08 01:13:02.673732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3af8b575089f'
down_revision = '0811bd7174d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=False))
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', mysql.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
