"""discount_exp_date removed from Product

Revision ID: 50dcec6a496d
Revises: 36e4d181d324
Create Date: 2023-06-26 14:54:39.638357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50dcec6a496d'
down_revision = '36e4d181d324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discount_exp_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_exp_date', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
