"""category parent_id foreign-key removed

Revision ID: 52c1dd975085
Revises: 78af1478b403
Create Date: 2023-06-28 22:09:49.452281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c1dd975085'
down_revision = '78af1478b403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_foreign_key('category_ibfk_1', 'category', ['parent_id'], ['id'])

    # ### end Alembic commands ###
