"""authority added to payment

Revision ID: 78a1a2cdb8b6
Revises: cee41a3cfd28
Create Date: 2023-07-09 17:31:24.281696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a1a2cdb8b6'
down_revision = 'cee41a3cfd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('authority')

    # ### end Alembic commands ###
