"""discount removed from order

Revision ID: 88691b0edb24
Revises: 92aeabe44a0f
Create Date: 2023-07-08 02:40:19.426627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88691b0edb24'
down_revision = '92aeabe44a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('payment',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('payment',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
