"""address phone an transferee added to Adress

Revision ID: 8bb35c196299
Revises: c3dd20aee283
Create Date: 2023-06-25 16:06:58.640900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb35c196299'
down_revision = 'c3dd20aee283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transferee', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=14), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('transferee')

    # ### end Alembic commands ###
