"""is_deleted removed from order

Revision ID: a08d46f473a6
Revises: 88691b0edb24
Create Date: 2023-07-08 02:45:06.436860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a08d46f473a6'
down_revision = '88691b0edb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
