"""transaction payment_id foreignkey

Revision ID: b6f0d31bbbad
Revises: 78a1a2cdb8b6
Create Date: 2023-07-09 17:58:01.535028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f0d31bbbad'
down_revision = '78a1a2cdb8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_ibfk_1', 'transaction', ['payment_id'], ['id'])

    # ### end Alembic commands ###
