"""initial migration(delete cascade(2))

Revision ID: ba8f6f7a775d
Revises: dd6a3187393c
Create Date: 2023-06-19 11:34:19.740364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8f6f7a775d'
down_revision = 'dd6a3187393c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_role_ibfk_2', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
