"""method removed from payment

Revision ID: cee41a3cfd28
Revises: 28ceacf0e53f
Create Date: 2023-07-09 17:15:46.190853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cee41a3cfd28'
down_revision = '28ceacf0e53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(length=20), server_default=sa.text("'Credit Card'"), nullable=True))

    # ### end Alembic commands ###
