"""initial migration(delete cascade)

Revision ID: dd6a3187393c
Revises: 6287f9f18846
Create Date: 2023-06-19 11:33:14.636385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd6a3187393c'
down_revision = '6287f9f18846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('cart_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cart', ['cart_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.drop_constraint('role_permission_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('role_permission_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_role_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_role_ibfk_1', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('user_role_ibfk_2', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('role_permission_ibfk_1', 'permission', ['permission_id'], ['id'])
        batch_op.create_foreign_key('role_permission_ibfk_2', 'role', ['role_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_ibfk_1', 'cart', ['cart_id'], ['id'])

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
