"""relations fixed

Revision ID: f221f5c12461
Revises: 45963cc5d2f9
Create Date: 2023-07-02 15:49:10.518567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f221f5c12461'
down_revision = '45963cc5d2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_role_ibfk_1', 'role', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
